import Navbar from "@/components/header/header";
import "@/styles/globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider"
import PageLayout from "@/components/layouts/pageLayout";

import { GeistSans } from "geist/font/sans";
export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark" 
            enableSystem
            disableTransitionOnChange
          >
        <Navbar/>

            <PageLayout>

        {children}
        </PageLayout>

        </ThemeProvider>
     

        </body>
    </html>
  );
}
