import Navbar from "@/components/navbar";
import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex-1 md:w-10/12 lg:w-8/12 mx-auto border-b-2">
     <Navbar/>

        {children}</body>
    </html>
  );
}
